

DROP TABLE orders IF EXISTS;
DROP TABLE divisions IF EXISTS;
DROP TABLE organization IF EXISTS;
DROP TABLE employees IF EXISTS;

DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;



CREATE TABLE organization
(
  id  INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255),
  legal_address VARCHAR(255),
  physical_address VARCHAR(255),
  manager_id INTEGER
);

CREATE TABLE employees
(
  id INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  middle_name VARCHAR(255),
  position VARCHAR(255),
  division_id INTEGER NOT NULL
);

CREATE TABLE divisions
(
  id  INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255),
  contacts  VARCHAR(255),
  manager_id INTEGER,
  organization_id INTEGER NOT NULL,
  parent_division_id INTEGER,
  FOREIGN KEY (manager_id) REFERENCES employees (id),
  FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE
);

CREATE TABLE orders
(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  subject     VARCHAR(255),
  author_id   INTEGER NOT NULL,
  executor_id INTEGER NOT NULL,
  deadline    TIMESTAMP,
  controlled  BOOLEAN,
  executed    BOOLEAN,
  text        VARCHAR(255)
);


ALTER TABLE organization
  ADD CONSTRAINT organization_manager FOREIGN KEY (manager_id) REFERENCES employees (id);

ALTER TABLE employees
  ADD CONSTRAINT division FOREIGN KEY (division_id) REFERENCES divisions (id);

ALTER TABLE orders
  ADD CONSTRAINT orders_author FOREIGN KEY (author_id) REFERENCES employees (id) ON DELETE CASCADE ;

ALTER TABLE orders
  ADD CONSTRAINT orders_executor FOREIGN KEY (executor_id) REFERENCES employees (id) ON DELETE CASCADE ;










